version: '2.1'

networks:
  pipebling: {}

services:
  database:
    container_name: database
    networks:
    - pipebling
    image: mongo
    ports:
    - 27018:27017
    environment:
      MONGO_INITDB_ROOT_DATABASE: pipebling
    command: mongod --smallfiles --logpath=/dev/null

  node:
    restart: always
    depends_on:
      - database
    networks:
      - pipebling
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/app
    environment:
      DSN: 'mongodb://database:27017/pipebling'
      BLING_KEY: 6380df6792789acdfc8e5d22309c9b551be816ac06f9aca926ee4207309e16b8fb55fba4
      PIPEDRIVE_KEY: 36ab53f24ef5c2f383c03a2c9a9deeb7c3d4f212
      PIPEDRIVE_DOMAIN: amravazzi
    ports:
      - '8099:8080'
    command: sh -c "yarn && yarn dev"
